# Git / GPG (includes SSH).
profiles:
  - ssh
read:
  - ~/.gitconfig
  - ~/.config/git
exec:
  - git
  - gpg
env:
  - GIT_AUTHOR_NAME
  - GIT_AUTHOR_EMAIL
  - GIT_COMMITTER_NAME
  - GIT_COMMITTER_EMAIL
